### PR TITLE
Introduce race result tools

### LINKED ISSUE #71: Time should not reset to zero within one SiCard
**Describe the bug**
Sometimes, the punch times don't increase monotonically. This is because of integer overflow.

**To Reproduce**
Go to the shell and do `test card` it occurs when the time exceeds `43200`.

**Expected behavior**
Postprocess SiCards to have clearTime <= checkTime <= startTime <= punch n time <= punch n+1 time <= finishTime

### PR DESCRIPTION
**Pull request by allestuetsmerweh**
...so e.g. in order to get the (most probably) real card data where the start time is the zero time:
`card.getNormalizedRaceResult()`

fixes #71

### CODE REVIEW

**Comment by guizmo51** [comment]
Ok I will try to review and test this PR. I have to modify my local config (I created alias with npm modules => a folder called @sportident with sportident and sportident-webusb inside]  and I cannot retrieve this PR for the moment.

**Comment by allestuetsmerweh** [comment]
It is well tested (coverage almost 100%). ...but does this API make sense to you?
e.g. do you find it easy to understand what is a "race result" and why we have "race result tools"?
do you think the functions in `raceResultTools` make sense?
do you think the `getNormalizedRaceResult()` convenience method on every SiCard makes sense?

**Comment by guizmo51** [comment]
From my point of view, the main thing / goal is to read card, and get datetime of punch. I think by default the timestamp field of punches should be filled with the timestamp of the punch not a modified value.

I read your code and I don't understand if raceResultTools become the default way to get punch time.

**Comment by allestuetsmerweh** [comment]
I wanted to make sure the BaseSiCard always has access to the original race result data (as read from the card). So that's why it's a function, `getNormalizedRaceResult` that calculates the times as the user wants to see them / the application needs them. As this functionality is complicated, I split it into different, independently testable functions and put them all into `raceResultTools`. Typically, an application should just call `getNormalizedRaceResult` and not need to deal with `raceResultTools`.

I believe one cannot find out the absolute timestamp (time since `1970-01-01 00:00:00`), but one is also hardly ever interested in that, no?

**Comment by guizmo51** [comment]
sorry, my english isn't perfect and I didn't understand very well. From what I understand it's OK.

**Comment by allestuetsmerweh** [comment]
Alright, then I'm going to merge this.

**Comment by guizmo51** [comment]
thanks ! I will update my npm dependencies when it will be available !

**Pull request merged**
