### PR TITLE
Fix SiTime

### LINKED ISSUE #85: Storage locations might be wrong
**To Reproduce**
1. Run testbench
2. simulate a station
3. simulate e.g. a SiCard10
=> What SiConfig+ reads differs somewhat from what's there in the siCard10Examples

**Expected behavior**
Storage locations are correct, i.e. the same as SiConfig+ reads.

### PR DESCRIPTION
**Pull request by allestuetsmerweh**
fixes #85

### CODE REVIEW

**Comment by guizmo51** [comment]
what should be "siProtocol.SiTimestamp" ? I updated using the last alpha release (3), in my case (in my current SIAC) I have no start time but the time for punches is time from 00:00 (and I still have the issue). I though we can get the date (like SI Config)

**Comment by allestuetsmerweh** [comment]
You only need `siProtocol.SiTimestamp`, if you use TypeScript. Until now, a time was a number, now it is a number or null (if it is `0xEEEE`).

I do not yet support the morning / afternoon bit and the weekday data in the SiTimestamp. If your numbers start from 0 (at start time), you probably call `getNormalizedRaceResult` instead of `getMonotonizedRaceResult`, or the card actually has these numbers.

**Comment by guizmo51** [comment]
I do not use getNormalizedRaceResult (I have a nice warning message because of no start time). Timestamp is from midnight (00:00)

**Comment by allestuetsmerweh** [comment]
Aha, you mean the formatting of the timestamps is not good? like, `7967` instead of `02:17:47`?
=> I didn't mean that with the issue description. I just saw that my code gives me a number while SiConfig gave me (empty). I solved that, now it's `null`.

If you want to format the number, you can copy this code: https://github.com/allestuetsmerweh/sportident.js/blob/master/packages/sportident/src/siProtocol.ts#L354
alternatively, I could export that in `utils`.

**Pull request merged**
